### ISSUE TITLE
Price Alert

### ISSUE THREAD

**Issue by moranimal22** [chanzer0/NBA-TopShot-Chrome-Extension#8]
Hi - love the tool so far!  great work.  The price list sorting and color coding is a game changer. 

On the price alert, I am struggling a little bit.  I have tested on about a dozen different moments and I cant seem to get it to work as I understand it should.  For example, I set the price threshold at $150 and the refresh interval at 2 seconds for a Lebron James moment.  After clicking "Begin Monitoring", I left the tab opened and continued using other tabs of TopShot in the same browser.  After a while, I wondered if it was working, so on a separate device I checked the same moment.  The price had fallen below $150 but I did not receive an alert.  

It seems like maybe the refresh functionality is not working as intended.  Could you please explain how it is supposed to work in more detail and look into whether it is functioning as expected. 

Thanks again for all your work on this.  It is a great tool and would be made SO much better with the use of price alert.

**Comment by chanzer0** [comment]
Hi there moranimal,

With the most recent updates to the price alert, price checking is done through NBA Top Shot's API, which means the page will not refresh unless your price threshold is met. I will update the documentation to reflect this. Can you try re-installing the extension as well, since there was a bug upon the first release where the price would come back null occasionally?

If the issue still persists, please write back and I can address it and/or include a video showing how to use it. 

Thanks,
Sean

**Comment by moranimal22** [comment]
Thanks for the quick response! I installed the latest version and retested.  That seemed to do the trick.  I think a video would be very helpful for other users to learn exactly how to use it.  

Thanks again for your help!

**Comment by chanzer0** [comment]
I will add a video to my to-do list, I agree that it would be very helpful. Enjoy the extension!
