### ISSUE TITLE
Monitoring is not working, no refresh

### ISSUE THREAD

**Issue by andreatopo** [chanzer0/NBA-TopShot-Chrome-Extension#9]
Hi I am testing this on two different pcs, my chrome is up to date, I tried reinstalling the extensions mulitple times with no success.
The price monitoring does not have the serial filter and the monitoring does not refresh the pages, it just sits there and it never restarts, I have tried a manualy refresh because it works for other people but it just sits there still. Let me know if you need any more info from me.
Thanks,

**Comment by chanzer0** [comment]
Hi andrea,

The extension now uses network calls (API calls) to fetch the price. This has many benefits over refreshing the page, including a much faster price-checking rate since you don't need to refresh the page. Serial number filtering is currently disabled due to a bug, but I hope to have it working soon again.

To verify your extension is working, press F12 and head to the Network tab. You should see network requests being made at the interval you specified. When the price check is satisfied, the page should reload and take you to dapper.

Can you verify that the extension is working? 

Thank you,
Sean.

**Comment by chanzer0** [comment]
I am closing this without a further follow-up
